Wikihow revision1, example 1
mideind/pisco pull request #1
Opened 2023-06-27 13:47 UTC by Mdan12

2023-06-27 13:49 UTC, haukurb requested changes

2023-06-27 13:49 UTC, haukurb commented on revision-1/wikihow/1.conversation.md
> +<|user|>
Fjarlægja

2023-06-27 13:49 UTC, haukurb commented on revision-1/wikihow/1.conversation.md
> +<|user|>
Þ.e. frá og með línu 1 til og með línu 6

2023-06-27 13:56 UTC, Mdan12 commented on revision-1/wikihow/1.conversation.md
> +<|user|>
Komið

2023-06-27 17:24 UTC, vthorsteinsson commented on revision-1/wikihow/1.conversation.md
> +5. Horfðu á misstök úr myndinni
Misstök -> mistök (nokkur tilvik)

2023-06-27 17:24 UTC, vthorsteinsson commented on revision-1/wikihow/1.conversation.md
> +Þú getur verið hræddur við uppvakninga, drauga, raðmorðingja, blóðsugu eða öðrum ógnvekjandi fyrirbærum eftir að hafa horft á hryllingsmynd. Viðurkenndu fyrir sjálfum þér að þú óttist einhvers. Það g
...önnur ógnvekjandi fyrirbæri...
...óttist eitthvað.
...heimili þitt...

2023-06-27 17:24 UTC, vthorsteinsson commented on revision-1/wikihow/1.conversation.md
> +Það getur hjálpað þér að tala við einhvern annan um óræðu tilfinningar þínar. Talaðu við systkini, foreldra eða hringdu eða sendu skilaboð á vini þína. Veldu einhvern sem þú getur treyst fyrir þessu.
...herbergi þess...
Nota íslenskar gæsalappir: „svona“

2023-06-27 17:24 UTC, vthorsteinsson commented on revision-1/wikihow/1.conversation.md
> +Vertu duglegur að minna þig sjálfan á að þú ert jafn öruggur fyrir og eftir að hafa horft á myndina. Haltu áfram að segja við sjálfan þig að þetta var bara mynd, ekki raunveruleiki og að myndin var g
...miklum peningum varið...
...sérstökum brellum...

2023-06-27 17:24 UTC, vthorsteinsson commented on revision-1/wikihow/1.conversation.md
> +Besta leiðin til að sigrast á óttanum er að horfast í augu við hann. Ef þú getur endurgert það sem þú óttast eða ímyndað þér það þá skaltu gera það. Andaðu í gegnum óttann og segðu við sjálfan þig að
...að fara að stækka...
...sem taka yfir bæinn...

2023-06-27 17:24 UTC, vthorsteinsson commented on revision-1/wikihow/1.conversation.md
> +Eftir að hafa horft á hryllingsmynd er sniðugt að horfa á eitthvað alveg í hina áttina. Horfðu á fyndin þátt eða mynd sem leiðir slæmu hugsanirnar eitthvert annað. Skapið þitt getur breyst mikið við
...á fyndinn þátt...
...við að hlæja...

2023-06-27 17:24 UTC, vthorsteinsson commented on revision-1/wikihow/1.conversation.md
> +Skrollaðu í gegnum samfélagsmiðla í símanum, leitaðu að fyndnum myndböndum á netinu eða skoðaðu vörur á uppáhaldsvefsíðum þínum. Það getur róað hugann að hugsa um eitthvað annað en myndina. Prófaðu a
Nota íslenskar gæsalappir
...vantar að hlæja.
...Skoðaðu myndir...

2023-07-04 12:39 UTC, haukurb approved these changes

2023-07-04 12:40 UTC, merged